import '~/js/components/burger';
import '~/js/components/expand.js';
import '~/js/components/dropdown';
import '~/js/components/collapse';
import '~/js/components/modal';
import '~/js/components/tooltip';
import '~/js/components/city';
import '~/js/components/menu';
import '~/js/components/autocomplete';
